name = "rawkode-academy-image-service"
pages_build_output_dir = "dist"
compatibility_date = "2023-01-23"
compatibility_flags = [ "nodejs_compat" ]

[observability]
enabled = true

[observability.logs]
enabled = true
destinations = [ "grafana-logs" ]

[observability.traces]
enabled = true
destinations = [ "grafana-traces" ]

[env.production]
compatibility_date = "2024-07-01"
