name: rawkode.academy/platform/emoji-reactions

# Force Deploy: 1

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/platform-emoji-reactions.yaml"
      - ".github/workflows/platform-service-deploy.yaml"
      - "projects/rawkode.academy/generators/projen-platform-service/**"
      - "projects/rawkode.academy/platform/emoji-reactions/**"
  pull_request:
    paths:
      - ".github/workflows/platform-emoji-reactions.yaml"
      - ".github/workflows/platform-service-deploy.yaml"
      - "projects/rawkode.academy/generators/projen-platform-service/**"
      - "projects/rawkode.academy/platform/emoji-reactions/**"

jobs:
  deploy:
    uses: ./.github/workflows/platform-service-deploy.yaml
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    with:
      service-name: emoji-reactions
      service-path: projects/rawkode.academy/platform/emoji-reactions
      has-write-model: true
